name: examples
source-dirs:
 - ./src
dependencies:
 - base
 - hylide
 - hylogen
 - vector-space
 - profunctors
 - lens
 - containers
 - nonempty-containers
library: {}
default-extensions:
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators
  - ImportQualifiedPost